#!/bin/bash

# Rural Hardware Store Setup Script
echo "Setting up Rural Hardware Store application..."

# Create project directory if it doesn't exist
mkdir -p /Users/dineshkumargopalakrishnan/RetailApp
cd /Users/dineshkumargopalakrishnan/RetailApp

# Clone the repository
echo "Cloning repository..."
git clone https://github.com/dineshgin/rural-hardware-store.git .

# Install dependencies
echo "Installing dependencies..."
npm install

# Create necessary directories
echo "Creating directories..."
mkdir -p src/database
mkdir -p src/styles
mkdir -p assets/icons

# Create a simple icon for the application
echo "Creating application icon..."
cat > assets/icons/icon.png << EOL
iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAsTAAALEwEAmpwYAAAF8WlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMjMtMDMtMTJUMTU6MzA6NDUrMDU6MzAiIHhtcDpNb2RpZnlEYXRlPSIyMDIzLTAzLTEyVDE1OjMxOjE3KzA1OjMwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDIzLTAzLTEyVDE1OjMxOjE3KzA1OjMwIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjY1OTM5YjFjLTJkMTEtNDZkYS1hYTEyLTNmMjI5ZGRiMzM2NyIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDo2NTkzOWIxYy0yZDExLTQ2ZGEtYWExMi0zZjIyOWRkYjMzNjciIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo2NTkzOWIxYy0yZDExLTQ2ZGEtYWExMi0zZjIyOWRkYjMzNjciPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjY1OTM5YjFjLTJkMTEtNDZkYS1hYTEyLTNmMjI5ZGRiMzM2NyIgc3RFdnQ6d2hlbj0iMjAyMy0wMy0xMlQxNTozMDo0NSswNTozMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKE1hY2ludG9zaCkiLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+
EOL

echo "Setup complete! You can now run the application with 'npm start'"